[input]
mol_path = "inp.mol"
par_path = "inp.par"
pos_path = "inp.pos"

[output]
csv_path = "out.csv"
dcd_path = "out.dcd"
log_path = "out.log"
rst_path = "out.rst"
xyz_path = "out.xyz"
csv_freq = 1000
dcd_freq = 100
rst_freq = 100

[dynamics]
time_step = 0.001
num_steps = 10000
temperature = 100.0
remove_com_v_freq = 100

[boundary]
length_x = 20.0
length_y = 20.0
length_z = 20.0

[rng]
seed = 0