[output]
out_csv_path = "out.csv"
out_dcd_path = "out.dcd"
out_log_path = "out.log"
out_xyz_path = "out.xyz"

[dynamics]
time_step = 0.001
num_steps = 10000
temperature = 100.0

[boundary]
length_x = 20.0
length_y = 20.0
length_z = 20.0
