[output]
out_csv_path = "out.csv"
out_dcd_path = "out.dcd"
out_log_path = "out.log"
out_xyz_path = "out.xyz"
out_csv_freq = 1000
out_dcd_freq = 100

[dynamics]
time_step = 0.001
num_steps = 10000
temperature = 100.0
remove_com_v_freq = 100

[boundary]
length_x = 20.0
length_y = 20.0
length_z = 20.0

[rng]
seed = 0